### ISSUE TITLE
Add --enableAdmin to all invocations of API server

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-compose-demo#110]
In all docker-compose-*.yaml files, change from 

https://github.com/Senzing/docker-compose-demo/blob/ed5b4f5530732946e23f88b617d6c3b95af2c363/resources/postgresql/docker-compose-rabbitmq-postgresql.yaml#L191-L202

to 

```yaml
  api:
    container_name: senzing-api-server
    command:
      - -httpPort
      - "8250"
      - -bindAddr
      - all
      - -iniFile
      - /etc/opt/senzing/G2Module.ini
      - -allowedOrigins
      - "*"
      - -enableAdmin
    depends_on:
```

Net:   Add the `-enableAdmin` parameter to the command.
