### ISSUE TITLE
Add flexibility to SENZING_DATABASE_URL for host and port

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-compose-demo#114]
**Is your feature request related to a problem? Please describe.**
Currently the `SENZING_DATABASE_URL` environment variable seen in docker-compose.yaml files look something like the following examples:

```yaml
      SENZING_DATABASE_URL: "db2://${DB2_USERNAME:-db2inst1}:${DB2_PASSWORD:-db2inst1}@senzing-db2:50000/${DB2_DB:-G2}"

      SENZING_DATABASE_URL: "mssql://${MSSQL_USERNAME:-sa}:${MSSQL_SA_PASSWORD:-Passw0rd}@senzing-mssql:1433/${MSSQL_DATABASE:-G2}"

      SENZING_DATABASE_URL: "mysql://${MYSQL_USERNAME:-g2}:${MYSQL_PASSWORD:-g2}@senzing-mysql:3306/${MYSQL_DATABASE:-G2}"

      SENZING_DATABASE_URL: "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@senzing-postgres:5432/${POSTGRES_DB:-G2}"
```

For flexibility in the host and port, they should look something more like:

```yaml
      SENZING_DATABASE_URL: "db2://${DB2_USERNAME:-db2inst1}:${DB2_PASSWORD:-db2inst1}@${DB2_HOST:-senzing-db2}:${DB2_PORT:-50000}/${DB2_DB:-G2}"

      SENZING_DATABASE_URL: "mssql://${MSSQL_USERNAME:-sa}:${MSSQL_SA_PASSWORD:-Passw0rd}@${MSSQL_HOST:-senzing-mssql}:${MSSQL_PORT:-1433}/${MSSQL_DATABASE:-G2}"

      SENZING_DATABASE_URL: "mysql://${MYSQL_USERNAME:-g2}:${MYSQL_PASSWORD:-g2}@${MYSQL_HOST:-senzing-mysql}:${MYSQL_PORT:-3306}/${MYSQL_DATABASE:-G2}"

      SENZING_DATABASE_URL: "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-senzing-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-G2}"
```

Also in MSSQL docker-compose.yaml files:

From 

```yaml
  mssql-create-db:
    command:
      - /opt/mssql-tools/bin/sqlcmd
      - -P
      - ${MSSQL_SA_PASSWORD:-Passw0rd}
      - -Q
      - "CREATE DATABASE G2"
      - -S
      - senzing-mssql
      - -U
      - sa
:
```
to 
```yaml
  mssql-create-db:
    command:
      - /opt/mssql-tools/bin/sqlcmd
      - -P
      - ${MSSQL_SA_PASSWORD:-Passw0rd}
      - -Q
      - "CREATE DATABASE G2"
      - -S
      - ${MSSQL_HOST:-senzing-mssql},${MSSQL_PORT:-1433}
      - -U
      - sa
:
```
Same change needed for `mssql-create-senzing:`
