### ISSUE TITLE
Add KAFKA_ADVERTISED_LISTENERS

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-compose-demo#158]
**Is your feature request related to a problem? Please describe.**
A Kafka producer  outside of the docker-compose formation stack isn't able to push messages to Kafka.

The following seemed to help  (Note:  `KAFKA_ADVERTISED_LISTENERS`)

```yaml
  kafka:
    container_name: senzing-kafka
    depends_on:
      - zookeeper
    environment:
#     See https://github.com/bitnami/bitnami-docker-kafka#configuration
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://senzing-kafka:9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_NUM_PARTITIONS: 5
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    image: bitnami/kafka:2.4.0
    networks:
      - backend
    ports:
      - 9092:9092
    restart: always
```

1. Determine if this change affects the behavior of the existing stack
2. Add it (`KAFKA_ADVERTISED_LISTENERS`) to all `docker-compose.yaml` files.
