### ISSUE TITLE
Use environment variables to configure Senzing API Server

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-compose-demo#189]
Similar to what is seen in Pull Request https://github.com/Senzing/docker-compose-demo/pull/190, modify all of the docker-compose.yaml files so that the `senzing/senzing-api-server` image is passed parameters via environment via environment variables rather than command-line parameters.

As an example, this is the general pattern of how it looks now:

```yaml
  api:
    container_name: senzing-api-server
    command:
      - -httpPort
      - "8250"
      - -bindAddr
      - all
      - -iniFile
      - /etc/opt/senzing/G2Module.ini
      - -allowedOrigins
      - "*"
      - -enableAdmin
    depends_on:
      - postgres
    environment:
#     See https://github.com/Senzing/senzing-api-server#configuration
      SENZING_DATABASE_URL: "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-senzing-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-G2}"
    image: senzing/senzing-api-server:${SENZING_DOCKER_IMAGE_VERSION_SENZING_API_SERVER:-2.6.1}
```

This issue will change that pattern to this example:

```yaml
  api:
    container_name: senzing-api-server
    depends_on:
      - postgres
    environment:
      SENZING_API_SERVER_ALLOWED_ORIGINS: '*'
      SENZING_API_SERVER_BIND_ADDR: 'all'
      SENZING_API_SERVER_ENABLE_ADMIN: 'true'
      SENZING_API_SERVER_PORT: '8250'
      SENZING_API_SERVER_SKIP_ENGINE_PRIMING: 'true'
      SENZING_API_SERVER_SKIP_STARTUP_PERF: 'true'
      SENZING_API_SERVER_INIT_JSON: >-
        {
          "PIPELINE": {
            "CONFIGPATH": "/etc/opt/senzing",
            "RESOURCEPATH": "/opt/senzing/g2/resources",
            "SUPPORTPATH": "/opt/senzing/data"
          },
          "SQL": {
            "CONNECTION": "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@senzing-postgres:5432:${POSTGRES_DB:-G2}/"
          }
        }
    image: senzing/senzing-api-server:${SENZING_DOCKER_IMAGE_VERSION_SENZING_API_SERVER:-2.6.1}
```

The 'command:` key is not used in the new pattern. The `SENZING_DATABASE_URL` environment variable is no longer used.

Note that the `api.environment.SENZING_API_SERVER_INIT_JSON.SQL.CONNECTION` value depends on the database used.  It will have the same format as the jupyter.environment.SENZING_SQL_CONNECTION value.

For bonus points, when working on this issue, the docker image versions can be updated to match the values in https://github.com/Senzing/knowledge-base/blob/master/lists/docker-versions-latest.sh
