### ISSUE TITLE
Add SENZING_ENGINE_CONFIGURATION_JSON to services

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-compose-demo#191]
Similar to the work done in https://github.com/Senzing/aws-cloudformation-ecs-poc-simple/issues/110,  certain `services:` in the docker-compose.yaml files need the ` SENZING_ENGINE_CONFIGURATION_JSON` environment variable defined.

Example:

```yaml
    environment:
      SENZING_ENGINE_CONFIGURATION_JSON: >-
        {
          "PIPELINE": {
            "CONFIGPATH": "/etc/opt/senzing",
            "RESOURCEPATH": "/opt/senzing/g2/resources",
            "SUPPORTPATH": "/opt/senzing/data"
          },
          "SQL": {
            "CONNECTION": "postgresql://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@senzing-postgres:5432:${POSTGRES_DB:-G2}/"
          }
        }
```

Note that the `SQL.CONNECTION` value is specific to each database.  It will be the value seen in services.jupyter.environment.SENZING_SQL_CONNECTION

The additional services that should have `SENZING_ENGINE_CONFIGURATION_JSON` defined are:

1. console
2. loader
3. redoer
4. api
5. sshd
6. jupyter
7. xterm
