### ISSUE TITLE
Add container entry for entity-search-webapp-console to yaml files

### ISSUE THREAD

**Issue by arawinters** [Senzing/docker-compose-demo#260]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/13721038/168700078-3a9f9444-132f-4f68-b78d-438cd320e482.png)

Add [entity-search-web-app-console](https://github.com/Senzing/entity-search-web-app-console) to example yaml files for integrated xterm from the webapp.

**Describe the solution you'd like**
User should be able to access the entity search webapp xterm console from inside the context of the webapp.

example of yaml entry to add:
```
  webapp:
    container_name: senzing-webapp
    depends_on:
      - api
      - webapp-console
    environment:
#     See https://github.com/Senzing/entity-search-web-app#configuration
      SENZING_API_SERVER_URL: http://senzing-poc-server:8250
      SENZING_WEB_SERVER_ADMIN_AUTH_MODE: NONE
      SENZING_WEB_SERVER_PORT: 8251
      SENZING_CONSOLE_SERVER_URL: ws://senzing-webapp-console:8273
    image: senzing/entity-search-web-app:${SENZING_DOCKER_IMAGE_VERSION_ENTITY_SEARCH_WEB_APP:-latest}
    networks:
      - backend
    ports:
      - 8251:8251
      - 8255:8255
    restart: always

  webapp-console:
      image: senzing/entity-search-web-app-console:${SENZING_DOCKER_IMAGE_VERSION_ENTITY_SEARCH_WEB_APP_CONSOLE:-latest}
      container_name: senzing-webapp-console
      environment:
        SENZING_CONSOLE_SERVER_PORT: 8273
      networks:
        - backend
      volumes:
        - ${SENZING_DATA_VERSION_DIR:-/opt/senzing/data/3.0.0}:/opt/senzing/data
        - ${SENZING_ETC_DIR:-/etc/opt/senzing}:/etc/opt/senzing
        - ${SENZING_G2_DIR:-/opt/senzing/g2}:/opt/senzing/g2
        - ${SENZING_VAR_DIR:-/var/opt/senzing}:/var/opt/senzing
      ports:
        - '8273:8273'
      restart: 'no'
```
