### ISSUE TITLE
Migrate to senzing/stream-producer

### ISSUE THREAD

**Issue by docktermj** [Senzing/docker-compose-demo#89]
**Is your feature request related to a problem? Please describe.**
[senzing/mock-data-generator](https://github.com/Senzing/mock-data-generator) is being deprecated in favor of [senzing/stream-producer](https://github.com/Senzing/stream-producer). The docker-compose formations should reflect this change.

#### Update docker-compose yaml files

:ballot_box_with_check: For all of the `docker-compose-XXX.yaml` files in https://github.com/Senzing/docker-compose-demo/tree/master/resources (There are about 35 of these files):

1. Replace `mockdata:` service with `streamproducer:` service using the format for the appropriate queue (RabbitMQ or Kafka).
   
##### RabbitMQ

```yaml
  producer:
    container_name: senzing-stream-producer
    depends_on:
      - rabbitmq
    environment:
#     See https://github.com/Senzing/stream-producer#configuration
      SENZING_DELAY_IN_SECONDS: 30
      SENZING_INPUT_URL: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
      SENZING_RABBITMQ_HOST: senzing-rabbitmq
      SENZING_RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD:-bitnami}
      SENZING_RABBITMQ_QUEUE: senzing-rabbitmq-queue
      SENZING_RABBITMQ_USERNAME: ${RABBITMQ_USERNAME:-user}
      SENZING_SUBCOMMAND: json-to-rabbitmq
    image: senzing/stream-producer:${SENZING_STREAM_PRODUCER_VERSION:-1.1.1}
    networks:
      - backend
    restart: on-failure
```

##### Kafka

```yaml
  producer:
    container_name: senzing-stream-producer
    depends_on:
      - kafka
    environment:
#     See https://github.com/Senzing/stream-producer#configuration
      SENZING_DELAY_IN_SECONDS: 30
      SENZING_KAFKA_BOOTSTRAP_SERVER: senzing-kafka:9092
      SENZING_KAFKA_TOPIC: senzing-kafka-topic
      SENZING_INPUT_URL: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
      SENZING_SUBCOMMAND: json-to-kafka
    image: senzing/stream-producer:${SENZING_STREAM_PRODUCER_VERSION:-1.1.1}
    networks:
      - backend
    restart: on-failure
```

#### Test docker-compose yaml files

:ballot_box_with_check: For all of the `README.md` files in https://github.com/Senzing/docker-compose-demo/tree/master/docs (There are about 15 of these files):

1. Bring the docker-compose formations up and see if the "entity-search-web-app" can find "Jessica White".

#### Update documentation

:ballot_box_with_check: For all of the `README.md` files in https://github.com/Senzing/docker-compose-demo/tree/master/docs (There are about 15 of these files):

1. Change the reference from
```
1. *[senzing/mock-data-generator](https://github.com/Senzing/mock-data-generator)*
```
to
```
1. *[senzing/stream-producer](https://github.com/Senzing/stream-producer)*
```

#### Update graphics

:ballot_box_with_check: For all of the `architecture.odg` files in https://github.com/Senzing/docker-compose-demo/tree/master/docs (There are about 15 of these files):

1. Use a program like "LibraOffice Draw" to modify `*.odg`:
    1. From "Docker container: senzing/mock-data-generator" to "Docker container: senzing/stream-producer"
    1. From "mock-data-generator" to "steam-producer"
1. Save the file in `*.odg` format **and** `*.png` format

See https://github.com/Senzing/stream-producer/issues/3

### Legend

:black_square_button: Not done
:ballot_box_with_check: Done
